project_id = "bzvlladhfqcaevtzoecc"

[functions.create-subscription-checkout]
verify_jwt = false

[functions.stripe-webhook]
verify_jwt = false

[functions.send-emails]
verify_jwt = false

[functions.lucy-chat]
verify_jwt = false

[functions.get-active-case]
verify_jwt = true

